"""empty message

Revision ID: 6802f54c5075
Revises: 
Create Date: 2021-05-29 13:46:37.638507

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6802f54c5075'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('yt_id', sa.String(length=15), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute(
        f'INSERT INTO clips ("title", "description", "yt_id", "date_added", "score") '
        f'VALUES ("Funky drums", "Amazing drummer", "LcapeUGqMhg", "{datetime.now()}", "0")'
    )

    op.execute(
        f'INSERT INTO clips ("title", "description", "yt_id", "date_added", "score") '
        f'VALUES ("Jojo Mayer Soundcheck", "At Berkley College of Music", "yVw8Kzjylt0", "{datetime.now()}", "0")'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clips')
    # ### end Alembic commands ###
